### ISSUE TITLE
作者在最开始生成音频的时候，温度、top_P 和 top_K 分别多少？

### ISSUE THREAD

**Issue by viewlei** [6drf21e/ChatTTS_Speaker#3]
我理解作者做了以下的工作：
1）采样 rand_spk；2）根据 rand_spk 和 温度、top_P、top_K 合成大量音频样本；3）用 ERes2NetV2 对音频进行分析

想问一下作者在最开始生成音频的时候，采用的 温度 、top_P、top_K分别是多少？这些信息对于用户进行复现是至关重要的。

**Comment by 6drf21e** [comment]
https://github.com/2noise/ChatTTS/pull/317/files#diff-87b0c55f3f791ef300350e1406721b9a7e056dcf903ef5c5a0e0e2a42f133ddaR67
和这里是一致的

**Comment by viewlei** [comment]
Thanks for reply!
